INSERT INTO story_table (story_id, story_for, story_by, title, description, is_positive, created_at)
VALUES
    ('550e8400-e29b-41d4-a716-446655440000', 'Mr. Rahman', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Great Teaching', 'Mr. Rahman has demonstrated an exceptional ability to make learning an engaging and enriching experience for every student in the classroom. From the very first lecture, it was clear that he is not only deeply knowledgeable about his subject but also passionate about imparting that knowledge to others. He uses a variety of teaching methods, blending traditional lectures with dynamic discussions and interactive activities that keep everyone’s attention firmly focused on the topics at hand. What stands out the most about Mr. Rahman is his commitment to ensuring that every concept is understood, not just memorized. Rather than rushing through the syllabus, he takes extra time to break down difficult ideas, using simple language and relatable examples that tie abstract concepts to real-world applications. For instance, during our recent unit on complex mathematics, he brought in relevant examples from everyday life, which made the theoretical concepts much more accessible and easier to grasp. He is also extremely receptive to student input and encourages everyone to participate in class discussions, fostering a respectful environment where every question is welcomed and valued. This has created a sense of community and collaboration among students that is quite rare. Beyond academics, Mr. Rahman is approachable and takes an active interest in our progress both inside and outside the classroom. He is always available for extra help after class and even checks in with students who might be struggling to offer personalized guidance. His dedication to teaching and his genuine care for his students’ success make him an outstanding educator. Over the course of this term, I have not only gained a deeper understanding of the subject matter but also developed a stronger love for learning, thanks to his consistently positive influence and teaching excellence.', true, CURRENT_TIMESTAMP),
    ('550e8400-e29b-41d4-a716-446655440001', 'Ms. Sultana', 'student2@example.com', 'Very Helpful', 'Finding a teacher as genuinely caring and attentive as Ms. Sultana is a rare and fortunate experience. Throughout the academic year, her willingness to help students succeed has stood out in countless ways. She not only arrives well-prepared for every lesson but is keenly aware of the individual needs of each student. No matter how busy she might be, she makes herself available before and after school, during breaks, and even responds to students’ email inquiries promptly. Her patient and supportive nature makes it easy for students to ask questions, regardless of how simple or complicated they may seem. In my experience, I have reached out to Ms. Sultana for clarification on multiple topics, sometimes after class or during her office hours, and never once did she show frustration or impatience. Instead, she provided clear and thorough explanations, often taking the extra step to present multiple perspectives or alternative ways of understanding a problem. This has greatly enhanced my confidence and ability to tackle challenging material. Her formal lessons are always meticulously structured, but she also recognizes that learning is not limited to the classroom environment. She encourages students to go beyond textbook knowledge, assigning thought-provoking projects and fostering a culture of inquiry. The one-on-one guidance she offers in these projects is invaluable, and her feedback is always constructive, thoughtful, and detailed, which allows students to learn from their mistakes and improve continuously. Moreover, Ms. Sultana’s encouragement and positivity go well beyond academics—she regularly shares motivational stories and helps students build resilience, preparing us for challenges in other areas of life as well. I am truly grateful to have been under her mentorship and would highly recommend her to any student hoping to thrive both academically and personally.', true, CURRENT_TIMESTAMP),
    ('550e8400-e29b-41d4-a716-446655440002', 'Mr. Karim', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Needs Improvement', 'Mr. Karim teaches with enthusiasm and covers a lot of ground during each session, which shows his strong command over the subject as well as his desire to impart as much knowledge as possible in the time allotted. However, I have found that the speed at which the lectures progress sometimes makes it difficult for many students, including myself, to fully absorb and process the content being taught. On several occasions, complex concepts were introduced and discussed in rapid succession, leaving little time for questions or in-depth exploration. While the syllabus is undoubtedly extensive and time is limited, slowing down the pace would provide more opportunities for student engagement and clarification of doubts. Another area for growth would be the inclusion of additional practical examples and exercises that can help bridge the gap between theory and real-world application. There have been several instances where students left the classroom with lingering uncertainties, simply because they did not have enough time to grasp the foundational ideas before moving on to the next topic. Mr. Karim is always approachable outside class and willing to provide explanations on an individual basis, which is greatly appreciated, but if more time was spent reinforcing concepts during lessons, perhaps through interactive activities or pausing for regular comprehension checks, it would benefit the class as a whole. The learning experience could be further enhanced if he were to solicit more feedback from students during lectures, creating a more interactive and responsive environment. Overall, with some adjustments to pacing and teaching style, Mr. Karim could make a significant improvement in making his classes more accessible and effective for everyone.', false, CURRENT_TIMESTAMP),
    ('550e8400-e29b-41d4-a716-446655440003', 'Ms. Rahima', 'student2@example.com', 'Engaging Class', 'Ms. Rahima possesses a unique talent for transforming her classroom into a vibrant, energetic, and welcoming space that motivates every student to participate actively. Her teaching style is far from traditional; rather than relying solely on lectures or textbooks, she incorporates group discussions, debates, visual aids, and real-life case studies to make the material come alive. During our classes, she never hesitates to pause and ask thought-provoking questions, prompting students to think critically about the topics under discussion. This approach not only deepens our understanding but also cultivates independent learning and curiosity. What truly distinguishes Ms. Rahima is her ability to make each student feel heard and valued—she remembers our names, interests, and learning preferences, and she goes out of her way to connect the course content to our individual experiences and aspirations. Her classes feel like a collaborative journey rather than a one-way transfer of information. In addition, she manages to strike a perfect balance between being approachable and maintaining high expectations. She gives constructive feedback, celebrates student achievements, and patiently works with those who might be struggling without making them feel embarrassed or marginalized. As a result, students who previously hesitated to participate now look forward to sharing their perspectives. Even complex or dry subjects seem interesting in her hands. Her passion for teaching, empathy, and creativity have left a lasting impression on me and my peers, making her one of the most effective and inspiring teachers I have ever had.', true, CURRENT_TIMESTAMP),
    ('550e8400-e29b-41d4-a716-446655440004', 'Mr. Rahman', 'student3@example.com', 'Good But Fast', 'Mr. Rahman has a remarkable gift for explaining concepts with clarity and enthusiasm, and he is deeply committed to fostering student success. His ability to convey complex material in an understandable way helps demystify challenging topics and provides a solid foundation for learners. However, one recurring challenge I have experienced—and one echoed by a number of my classmates—is the pace at which he moves through particularly dense or intricate segments of the curriculum. While his intentions to cover all necessary material thoroughly are appreciated, the briskness sometimes leaves students feeling overwhelmed, especially when new topics are introduced before previous ones have been fully absorbed. Slowing down at critical junctures, perhaps by incorporating more opportunities for review or practice, would make it easier for everyone to keep up and feel confident in their understanding. Mr. Rahman does an excellent job of inviting questions during lectures, but time constraints often prevent a deeper exploration into important issues raised by students. This means some nuanced points may not receive the attention they deserve. Implementing periodic review sessions or allocating additional time for Q&A could be incredibly beneficial for overall comprehension. Despite this, his support outside of class is outstanding: he is approachable, encourages further inquiry, and always seeks ways to help students succeed. With minor adjustments to pacing and an added emphasis on consolidating knowledge before progressing, Mr. Rahman’s teaching could go from very good to truly exceptional.', false, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440005', 'Ms. Sultana', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Inspiring Mentor', 'Ms. Sultana consistently goes above and beyond to support her students, not just academically but personally. Her ability to identify each student’s strengths and weaknesses allows her to tailor her guidance in a way that truly resonates. She often shares stories of perseverance and success that motivate us to push through challenges. Her mentorship has helped me become more confident and goal-oriented.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440006', 'Mr. Karim', 'student2@example.com', 'Too Theoretical', 'While Mr. Karim’s lectures are rich in theoretical content, they often lack practical application. Many students struggle to connect the abstract ideas to real-world scenarios. Including more hands-on examples or case studies could significantly improve comprehension and engagement. His willingness to help outside class is commendable, but the in-class experience needs more balance.', false, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440007', 'Ms. Rahima', 'student3@example.com', 'Creative Approach', 'Ms. Rahima’s teaching style is refreshingly creative. She uses storytelling, role-play, and multimedia to make even the driest topics engaging. Her classroom feels like a space where curiosity is celebrated, and learning is a shared adventure. Her feedback is always constructive and personalized, helping students grow in confidence and skill.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440008', 'Mr. Rahman', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Supportive but Rushed', 'Mr. Rahman is incredibly supportive and knowledgeable, but his lectures sometimes feel rushed. Students often find it difficult to keep up with the pace, especially during complex topics. A slower, more interactive approach would enhance understanding. Nonetheless, his dedication and availability outside class are deeply appreciated.', false, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440009', 'Ms. Sultana', 'student3@example.com', 'Empowering Educator', 'Ms. Sultana empowers her students by encouraging independent thinking and self-expression. Her classroom is a safe space where ideas are welcomed and explored. She provides thoughtful feedback and celebrates small victories, which boosts morale and motivation. Her influence has helped me become a more confident learner.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440010', 'Mr. Karim', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Needs More Interaction', 'Mr. Karim’s lectures are informative but often lack student interaction. Encouraging questions and discussions during class could make the sessions more engaging and effective. While he is approachable outside class, integrating more dialogue into the lessons would benefit the learning experience.', false, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440011', 'Ms. Rahima', 'student2@example.com', 'Inclusive Teaching', 'Ms. Rahima excels at creating an inclusive learning environment. She adapts her teaching to accommodate different learning styles and ensures that every student feels heard. Her use of diverse materials and collaborative activities makes learning enjoyable and effective. She’s a true asset to our academic community.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440012', 'Mr. Rahman', 'student2@example.com', 'Clarity with Speed', 'Mr. Rahman explains concepts clearly and passionately, but the speed of delivery can be overwhelming. Slowing down during key topics and incorporating more review sessions would help students retain information better. His commitment to student success is evident, and with slight adjustments, his teaching could be even more impactful.', false, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440013', 'Ms. Sultana', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Thoughtful Guidance', 'Ms. Sultana provides thoughtful and personalized guidance that helps students navigate both academic and personal challenges. Her ability to listen and respond with empathy makes her a trusted mentor. She encourages critical thinking and self-reflection, which has helped me grow immensely.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440014', 'Mr. Karim', 'student3@example.com', 'Room for Improvement', 'Mr. Karim’s lectures are packed with information, but the lack of pacing and interactive elements makes it hard to follow. Incorporating more student feedback and practical exercises could make his classes more engaging. He’s clearly knowledgeable, and with some tweaks, his teaching could be much more effective.', false, CURRENT_TIMESTAMP),
    ('550e8400-e29b-41d4-a716-446655440025', 'Ms. Sultana', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Compassionate and Consistent', 'Ms. Sultana consistently demonstrates a deep commitment to her students’ well-being and academic growth. Her classes are well-structured, and she always ensures that no one is left behind. Her calm demeanor and empathetic approach create a nurturing environment where students feel safe to express themselves and ask questions.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440026', 'Mr. Karim', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Strong Content, Needs More Flexibility', 'Mr. Karim’s subject knowledge is impressive, and he delivers content with clarity. However, his lectures could benefit from more flexibility and student interaction. Encouraging questions during class and incorporating real-life examples would make the sessions more engaging and relatable.', false, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440027', 'Ms. Rahima', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Dynamic and Inclusive', 'Ms. Rahima’s classroom is a hub of creativity and collaboration. She fosters an inclusive atmosphere where every student feels valued. Her use of diverse teaching strategies, from group projects to multimedia presentations, keeps the learning process exciting and effective.', true, CURRENT_TIMESTAMP),

    ('550e8400-e29b-41d4-a716-446655440028', 'Mr. Rahman', '7aEqxShNFnwhmXhC5uheYtSbPYxbiCKd5aKhua8ewfM=', 'Excellent Clarity, Slightly Rushed', 'Mr. Rahman explains topics with remarkable clarity and enthusiasm. However, the pace of his lectures can sometimes be brisk, making it hard for students to fully digest complex material. Slowing down during key sections and allowing more time for questions would enhance the overall learning experience.', false, CURRENT_TIMESTAMP);

insert into user_table(user_id,username,password,role)
values
('79d96e2a-b9c3-4bbd-950d-63452b282644', 'root',	'$2a$10$ZMKzPyiFvAl8kDZS4mPFk.KrHBQ18jhs5Tj8/xBPbyQ5wUzw7hSyq','ROLE_USER'),
('79d96e2a-b9c3-4bbd-950d-63452b282645', 'admin',	'$2a$10$ZMKzPyiFvAl8kDZS4mPFk.KrHBQ18jhs5Tj8/xBPbyQ5wUzw7hSyq','ROLE_ADMIN');